#ifndef CONFIG_H_INCLUDED
#define CONFIG_H_INCLUDED

#define ZLAB_USE_PWM_OUT	1
#define ZLAB_USE_DIGIT_IN 	1

#define ZLAB_HEAP_SIZE		(24*1024)

// For future
#define ZLAB_HEAP_BLOCK_SIZE	256
#define ZLAB_HEAP_BLOCK_COUNT	10

#endif //CONFIG_H_INCLUDED
